# Generated by Django 4.0.3 on 2022-05-25 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('tourTime', models.FloatField(null=True)),
                ('tourLatitue', models.FloatField(blank=True)),
                ('tourLongitude', models.FloatField(blank=True)),
                ('tour_url', models.URLField(blank=True, default='', max_length=400, null=True, verbose_name='관광지 URL')),
                ('visitCnt', models.IntegerField(null=True)),
            ],
        ),
    ]
