# Generated by Django 4.0.3 on 2022-05-25 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='tourLatitue',
            new_name='tourLatitude',
        ),
    ]
